# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and run reciept printer

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout branch
      env:
        BRANCH: ${{ github.head_ref || github.ref_name }}
      run: |
        cd /home/tim/receipt-printer
        git fetch origin
        git checkout "$BRANCH"
        git pull origin "$BRANCH"

    - name: Install dependencies
      run: |
        /home/tim/venv/bin/pip install -r requirements.txt

    - name: Restart service
      run: sudo systemctl restart receipt-printer.service
