# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build and run reciept printer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Pull latest code
      run: |
        cd /home/tim/receipt-printer
        git pull

    - name: Install dependencies
      run: |
        /home/tim/venv/bin/pip install -r requirements.txt

    - name: Restart service
      run: sudo systemctl restart receipt-printer.service
